export const USER_SIGN_UP = 'USER_SIGN_UP'
export const USER_SIGN_IN = 'USER_SIGN_IN'

export const ADD_PERSONAL_DETAILS='ADD_PERSONAL_DETAILS'
export const GET_ALL_COLLEGES = 'GET_ALL_COLLEGES';
export const GET_ALL_BRANCHES = 'GET_ALL_BRANCHES';
export const ADD_ACADEMIC_DETAILS = 'ADD_ACADEMIC_DETAILS';
export const ADD_EMAIL = 'ADD_EMAIL'